# Generated by Django 5.2 on 2025-05-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_main_review_alter_review_author_review_main_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='main_review',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Main_Review',
        ),
    ]
